/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_logger.h"

bool_t
xdr_send_log_params (XDR *xdrs, send_log_params *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->filename, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->date_time, 22))
		 return FALSE;
	return TRUE;
}
