/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_LOGGER_H_RPCGEN
#define _RPC_LOGGER_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct send_log_params {
	char *username;
	char *operation;
	char *filename;
	char *date_time;
};
typedef struct send_log_params send_log_params;

#define RPC_LOGGER 100495924
#define RPC_LOGGER_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define send_log_rpc 1
extern  enum clnt_stat send_log_rpc_1(struct send_log_params , int *, CLIENT *);
extern  bool_t send_log_rpc_1_svc(struct send_log_params , int *, struct svc_req *);
extern int rpc_logger_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define send_log_rpc 1
extern  enum clnt_stat send_log_rpc_1();
extern  bool_t send_log_rpc_1_svc();
extern int rpc_logger_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_send_log_params (XDR *, send_log_params*);

#else /* K&R C */
extern bool_t xdr_send_log_params ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_LOGGER_H_RPCGEN */
