/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "../rpc_logger.h"
#include <stdio.h>
#include <string.h>

bool_t
send_log_rpc_1_svc(struct send_log_params args, int *result,  struct svc_req *rqstp)
{
	bool_t retval = TRUE;
	printf("%s\t%s\t", args.username, args.operation);
	if (strcmp(args.operation, "PUBLISH") == 0 || strcmp(args.operation, "DELETE") == 0){
		printf("%s\t", args.filename);
	}
	printf("%s\n", args.date_time);
	*result = 0;

	return retval;
}

int
rpc_logger_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);


	return 1;
}
