/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "../rpc_logger.h"
#include "../comm_sock.h"
#include <string.h>


int
send_log(char *username, char *operation, char *filename, char *date_time){
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	struct send_log_params send_log_rpc_1_args;
	char *env_ip_log_rpc;

	// inicializar send_log_rpc_1_args con los argumentos de la función aquí
	send_log_rpc_1_args.username = (char *)malloc(strlen(username)*sizeof(char));
	strcpy(send_log_rpc_1_args.username, username);
	send_log_rpc_1_args.operation = (char *)malloc(strlen(operation)*sizeof(char));
	strcpy(send_log_rpc_1_args.operation, operation);
	if (strcmp(operation, "PUBLISH") == 0 || strcmp(operation, "DELETE") == 0){
		send_log_rpc_1_args.filename = (char *)malloc(strlen(filename)*sizeof(char));
		strcpy(send_log_rpc_1_args.filename, filename);
	}else{
		send_log_rpc_1_args.filename = "";
	}
	send_log_rpc_1_args.date_time = (char *)malloc(strlen(date_time)*sizeof(char));
	strcpy(send_log_rpc_1_args.date_time, date_time);


	// Obtener la variable de entorno
	env_ip_log_rpc = getenv("LOG_RPC_IP");
    if (env_ip_log_rpc == NULL){
        perror("LOG_RPC_IP no definida");
        return -1;
    }

	clnt = clnt_create (env_ip_log_rpc, RPC_LOGGER, RPC_LOGGER_VER, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (env_ip_log_rpc);
		return -1;
	}

	retval_1 = send_log_rpc_1(send_log_rpc_1_args, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
		return -1;
	}

	clnt_destroy (clnt);

	free(send_log_rpc_1_args.username);
	free(send_log_rpc_1_args.operation);
	if (strcmp(operation, "PUBLISH") == 0 || strcmp(operation, "DELETE") == 0){
		free(send_log_rpc_1_args.filename);
	}
	free(send_log_rpc_1_args.date_time);

	return 0;

}
