/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "../rpc_logger.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
send_log_rpc_1(struct send_log_params args, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, send_log_rpc,
		(xdrproc_t) xdr_send_log_params, (caddr_t) &args,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
